### ISSUE TITLE
dependency on blasr prevented from compiling

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbdagcon#22]
./configure.py --no-pbbam 
make
make -C src/cpp
make[1]: Entering directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
g++ -O3 -std=c++11 -Wall -Wuninitialized -pedantic -Ithird-party  -c -o main.o main.cpp
main.cpp:59:35: fatal error: tuples/TupleMetrics.hpp: No such file or directory
 #include "tuples/TupleMetrics.hpp"
                                   ^
compilation terminated.
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
make: *** [cpp-github] Error 2

**Comment by pb-cdunn** [comment]
You need to build the submodules first. See `travis.sh`:
```
make init-submodule
```
That will update the git submodules and build them.

Yeah, not obvious, but it works. You should see `defines.mk` in both the blasr dir and libcpp dir.

**Comment by pb-cdunn** [comment]
And you need to pass `--sub` to `configure.py`, as in `travis.sh`.

**Comment by kemin711** [comment]
I tried  ./configure.py --gtest --sub --no-pbbam
Do I then clone the libcpp into the subdirectory blasr_libcpp that is empty now?

**Comment by kemin711** [comment]
Now I clone the blasr_libcpp into the current directory: 
git clone git://github.com/PacificBiosciences/blasr_libcpp.git
make init-submodule
make: *** No rule to make target `init-submodule'.  Stop.

I must be over looking the instruction.

**Comment by kemin711** [comment]
You have to issue the command in the parent directory, then it can be easily made.  My mistake is making it inside the libcpp directory.

**Comment by pb-cdunn** [comment]
Oh, good! We should make that more clear in the docs. I think Vlad is updating those as I type this.

**Comment by kemin711** [comment]
I am a programmer.  I usually type vague English, just after a while I have to figure out what I meant in the first place.  I fully understand this. Kemin Zhou
858 771-3269
