### ISSUE TITLE
failed to clone the project

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbdagcon#23]
git clone git@github.com:PacificBiosciences/blasr.git blasr --recursive
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/.git/
Enter passphrase for key '/home/users/zhouk15/.ssh/id_rsa':
remote: Counting objects: 2727, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2727 (delta 2), reused 0 (delta 0), pack-reused 2720
Receiving objects: 100% (2727/2727), 2.57 MiB | 110 KiB/s, done.
Resolving deltas: 100% (1384/1384), done.
Submodule 'libcpp' (git://github.com/PacificBiosciences/blasr_libcpp.git) registered for path 'libcpp'
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/libcpp/.git/
fatal: read error: Connection timed out
Clone of 'git://github.com/PacificBiosciences/blasr_libcpp.git' into submodule path 'libcpp' failed

**Comment by pb-cdunn** [comment]
Looks like an intermittent service failure. Unless China is attacking GitHub, just try again. `git init-submodule`. Or just `git submodule update --init`.

**Comment by pb-cdunn** [comment]
Reopen if it fails again, repeatably.

**Comment by kemin711** [comment]
Sorry, put in the wrong hub.
