### ISSUE TITLE
configure.py crashed

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbdagcon#24]
This problem may be related to my set up because I was able to build the whole packages only with minor modifications yesterday on a different machine.
This particular VM is certainly different from the one that I can successfully build.
 ```
./configure.py --sub --no-pbbam
bash -c 'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper:]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d
" ${rel/./};; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac' 2>/dev/null
Traceback (most recent call last):
  File "./configure.py", line 269, in <module>
    main(*sys.argv)
  File "./configure.py", line 264, in main
    set_defs_defaults(envin, conf.no_pbbam)
  File "./configure.py", line 219, in set_defs_defaults
    setifenvf(defaults, env, 'OS_STRING', get_OS_STRING)
  File "./configure.py", line 122, in setifenvf
    envout[key] = ifenvf(envin, key, func)
  File "./configure.py", line 120, in ifenvf
    return func()
  File "./configure.py", line 111, in get_OS_STRING
    return shell(G_BUILDOS_CMD)
  File "./configure.py", line 30, in shell
    raise Exception('%d <-| %r' %(status, cmd))
Exception: 32512 <-| 'bash -c \'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper:]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d\n" ${rel/./};; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac\' 2>/dev/null'
```

**Comment by pb-cdunn** [comment]
We don't even use lsb_release info now. I've been meaning to remove that. (And I wish I had removed the 2>/dev/null part. It's copy/pasted from elsewhere.) Just a minute...

**Comment by kemin711** [comment]
Yes, the problem is lsb_release, so I will modify the configure script?

 bash -c 'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper    :]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d\n" ${rel/./}    ;; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac' 2>/dev/null
zhouk15@rpbuv009:~/remoteh/src/pbdagcon$ bash -c 'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper    :]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d\n" ${rel/./}    ;; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac'
bash: lsb_release: command not found
tr: invalid character class `upper    '
