### ISSUE TITLE
failed to make

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbdagcon#26]
I was able to make the pbdagcon package from a different machine.
But now I am getting deeper and deeper into the linking errors.
I think you may be able to help me a little.  I think the linking error is to the HDF5 package.
These are the libs related to HDF5:
```
libblasr.a      libhdf5_cpp.so.10      libhdf5_hl_cpp.so.10      libhdf5.la         libpbdata.so
libblasr.so     libhdf5_cpp.so.10.0.1  libhdf5_hl_cpp.so.10.0.1  libhdf5.settings   libpbihdf.a
libhdf5.a       libhdf5_hl.a           libhdf5_hl.la             libhdf5.so         libpbihdf.so
libhdf5_cpp.a   libhdf5_hl_cpp.a       libhdf5_hl.so             libhdf5.so.10      python2.7
libhdf5_cpp.la  libhdf5_hl_cpp.la      libhdf5_hl.so.10          libhdf5.so.10.0.1
libhdf5_cpp.so  libhdf5_hl_cpp.so      libhdf5_hl.so.10.0.1      libpbdata.a
```
Possibly I did not make these library with the proper linking or compiler tags.

**Comment by kemin711** [comment]
First few lines of the make errors:

make
make -C src/cpp
make[1]: Entering directory `/remote/RSU/home/zhouk15/src/pbdagcon/src/cpp'
g++ -Wl,--no-as-needed -o pbdagcon Alignment.o AlnGraphBoost.o BlasrM5AlnProvider.o main.o SimpleAligner.o -L ../../blasr_libcpp/alignment -L ../../blasr_libcpp/pbdata -L ../../blasr_libcpp/hdf -L/remote/RSU/sw-cache/metag/lib -lhdf5 -lblasr -lpbdata
../../blasr_libcpp/alignment/libblasr.so: undefined reference to `vtable for HDFData'
../../blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::H5File::~H5File()'
../../blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::StrType::StrType(int, unsigned long const&)'
../../blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::DataSet::getSpace() const'
../../blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::DSetCreatPropList::DSetCreatP

**Comment by pb-cdunn** [comment]
Look at `travis.sh`. It runs `make init-submodule`, which runs the `build-submodule` target, which does this:
```
build-submodule:
        cd blasr_libcpp; NOHDF=1 NOPBBAM=1 ./configure.py
        ${MAKE} -C blasr_libcpp/pbdata libpbdata.a
        ${MAKE} -C blasr_libcpp/alignment libblasr.a
```
It does not use HDF5 at all, nor pbbam. That's the currently supported way to build **pbdagcon**.

**Comment by kemin711** [comment]
Thanks. Kemin Zhou
858 771-3269
