### ISSUE TITLE
make file error at line 18

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbdagcon#27]
I just clone the brand new repository
```
 ./configure.py --sub --no-pbbam
writing to '/remote/RSU/home/zhouk15/src/pbdagcon/defines.mk'
"""
LIBBLASR_INCLUDE     ?= /remote/RSU/home/zhouk15/src/pbdagcon/blasr_libcpp/alignment
LIBBLASR_LIB         ?= /remote/RSU/home/zhouk15/src/pbdagcon/blasr_libcpp/alignment
LIBBLASR_LIBFLAGS    ?= -lblasr
LIBPBDATA_INCLUDE    ?= /remote/RSU/home/zhouk15/src/pbdagcon/blasr_libcpp/pbdata
LIBPBDATA_LIB        ?= /remote/RSU/home/zhouk15/src/pbdagcon/blasr_libcpp/pbdata
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_INCLUDE    ?=
LIBPBIHDF_LIB        ?=
"""
zhouk15@rpbuv009:~/remoteh/src/pbdagcon$ make init-submodule
makefile:18: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```
I also noticed the LIBPBIHDF_ Flags not set, the configure.py --help does not have an instruction for how to set this flag.  Is this the HDF5 library that you can download from https://www.hdfgroup.org/HDF5/

**Comment by kemin711** [comment]
Actually there are many lines that should start with TAB and was replaced with space.

**Comment by pbjd** [comment]
I'm fixing this now

**Comment by pb-cdunn** [comment]
wait...i've got it already.

**Comment by kemin711** [comment]
I am able to build successfully.  Thanks for the work.  You can close this issue.

**Comment by kemin711** [comment]
The TAB over Space is the more frequently cursed feature of Make.  Python also depends on indentation, but is more forgiving.

**Comment by pb-cdunn** [comment]
I stupidly ran `git stripspace` when I usually use `perl -pie 's/\s+$/\n/;`.

There is still a problem in the gcc build for configure.py. clang works already. Fixing gcc...

**Comment by kemin711** [comment]
Christopher,
I have mentioned before about not being able to clone certain modules qith git 1.7.1 and able to do so with git 1.9.1.  Sometimes, I can pull the individual modules independently.  This is reproducible for certain module but not all.  This is not a bug, and it must be some problem from gitHub.  It is a little bit annoying. Kemin Zhou
858 771-3269

**Comment by pb-cdunn** [comment]
The config problem worked on a rebuild. No issue. Closing.

kemin, yes, that's annoying. But can you use a more recent git?

**Comment by kemin711** [comment]
I am pushing for it and informed IT.  We are using Centos 6.5.  My solution right now is to use my home machine to clone, the scp the tar ball to my work machine.

**Comment by pb-cdunn** [comment]
Was the problem only with `--recursive`?

**Comment by kemin711** [comment]
Yes.  It just hung there with git 1.7.1, then time out when pulling not all but some submodules.  For some reason, my home machine which is using git 1.9.1 can pull the source code in a matter of a few seconds.

**Comment by pb-cdunn** [comment]
What if you simply don't use `--recursive`?
```
git clone pbdagcon
cd pbdagcon
git submodule update --init
```
