### ISSUE TITLE
failed to make

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbdagcon#36]
./configure.py
writing to '/home/kzhou/src/metag/pbdagcon/defines.mk'
"""
DALIGNER_INCLUDE     ?= ${DALIGNER_SRC}
DALIGNER_SRC         ?= /home/kzhou/src/metag/pbdagcon/../DALIGNER
DAZZ_DB_INCLUDE      ?= ${DAZZ_DB_SRC}
DAZZ_DB_SRC          ?= /home/kzhou/src/metag/pbdagcon/../DAZZ_DB
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
HTSLIB_LIBFLAGS      ?= -lhts
LIBBLASR_LIBFLAGS    ?= -lblasr
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
PBBAM_LIBFLAGS       ?= -lpbbam
ZLIB_LIBFLAGS        ?= -lz
"""
kzhou@jinshou:~/src/metag/pbdagcon$ make
make -C src/cpp
make[1]: Entering directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
g++ -O3 -std=c++11 -Wall -Wuninitialized -pedantic -MMD -MP -I/home/kzhou/src/metag/pbdagcon/../DAZZ_DB -I/home/kzhou/src/metag/pbdagcon/../DALIGNER -isystem.//third-party  -c -o Alignment.o Alignment.cpp
g++ -O3 -std=c++11 -Wall -Wuninitialized -pedantic -MMD -MP -I/home/kzhou/src/metag/pbdagcon/../DAZZ_DB -I/home/kzhou/src/metag/pbdagcon/../DALIGNER -isystem.//third-party  -c -o AlnGraphBoost.o AlnGraphBoost.cpp
g++ -O3 -std=c++11 -Wall -Wuninitialized -pedantic -MMD -MP -I/home/kzhou/src/metag/pbdagcon/../DAZZ_DB -I/home/kzhou/src/metag/pbdagcon/../DALIGNER -isystem.//third-party  -c -o BlasrM5AlnProvider.o BlasrM5AlnProvider.cpp
g++ -O3 -std=c++11 -Wall -Wuninitialized -pedantic -MMD -MP -I/home/kzhou/src/metag/pbdagcon/../DAZZ_DB -I/home/kzhou/src/metag/pbdagcon/../DALIGNER -isystem.//third-party  -c -o main.o main.cpp
main.cpp:59:35: fatal error: tuples/TupleMetrics.hpp: No such file or directory
 #include "tuples/TupleMetrics.hpp"
                                   ^
compilation terminated.
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
make: *** [cpp] Error 2

**Comment by kemin711** [comment]
Looks like the project might need to be factored a little bit.  The required header file is in another project:
/blasr/libcpp/alignment/tuples/TupleMetrics.hpp
It might be abstract the blasr project into a library.

**Comment by pb-cdunn** [comment]
Look at `travis.sh`. That's what we run automatically, so it should work for you.

**Comment by kemin711** [comment]
Looks the make file is missing some library reference:
g++ -Wl,--no-as-needed -o pbdagcon Alignment.o AlnGraphBoost.o BlasrM5AlnProvider.o main.o SimpleAligner.o  -L/home/kzhou/lib -L/usr/local/lib -lblasr -lpbdata
/home/kzhou/lib/libblasr.so: undefined reference to `vtable for HDFData'
/home/kzhou/lib/libblasr.so: undefined reference to `H5::H5File::~H5File()'
/home/kzhou/lib/libblasr.so: undefined reference to `H5::StrType::StrType(int, unsigned long const
...  A lots more not shown

After adding -lhdf5_cpp -lhdf5, I am still getting more linking errors:
g++ -Wl,--no-as-needed -o pbdagcon Alignment.o AlnGraphBoost.o BlasrM5AlnProvider.o main.o SimpleAligner.o  -L/home/kzhou/lib -L/usr/local/lib -lhdf5_cpp -lhdf5 -lblasr -lpbdata
/home/kzhou/lib/libblasr.so: undefined reference to `vtable for HDFData'
/home/kzhou/lib/libblasr.so: undefined reference to `HDFNewBasReader::Close()'
/home/kzhou/lib/libblasr.so: undefined reference to `HDFAtom<std::string>::Read(std::string&)'
/home/kzhou/lib/libblasr.so: undefined reference to `vtable for HDFGroup'
/home/kzhou/lib/libblasr.so: undefined reference to `HDFData::InitializeDataset(HDFGroup&, std::st

**Comment by kemin711** [comment]
After running travis.sh got different error messages:

/boost_1_58_0-headersonly -isystem.//third-party  -c -o dazcon.o dazcon.cpp
/home/kzhou/src/metag/pbdagcon/DALIGNER/align.c:61:16: fatal error: DB.h: No such file or directory
 #include "DB.h"
                ^
compilation terminated.
/home/kzhou/src/metag/pbdagcon/DAZZ_DB/DB.c: In function ‘Load_QVs’:
/home/kzhou/src/metag/pbdagcon/DAZZ_DB/DB.c:814:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
In file included from DazAlnProvider.cpp:45:0:
DazAlnProvider.hpp:52:16: fatal error: DB.h: No such file or directory
 #include "DB.h"
                ^
/home/kzhou/src/metag/pbdagcon/DAZZ_DB/DB.c:818:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
compilation terminated.
/home/kzhou/src/metag/pbdagcon/DAZZ_DB/DB.c:823:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
 File `all' does not exist.
   File `dazcon' does not exist.
make[1]: *** [align.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [DazAlnProvider.o] Error 1
In file included from dazcon.cpp:57:0:
DazAlnProvider.hpp:52:16: fatal error: DB.h: No such file or directory
 #include "DB.h"
                ^
compilation terminated.
make[1]: *** [dazcon.o] Error 1
make[1]: Leaving directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
make: *** [cpp] Error 2

**Comment by pb-cdunn** [comment]
That's interesting. What do you get from this?
```
git rev-parse HEAD
git submodule status
```

**Comment by kemin711** [comment]
git rev-parse HEAD
345498238728b741fbf5c10b96bf0904f8265ab1
kzhou@jinshou:~/src/metag/pbdagcon$ git submodule status
 dc506e67938c1c923ebb7e43ff8ce32ec923d8ba DALIGNER (heads/master)
 337a0ee0e77624094221577bdaa38c79b5444d91 DAZZ_DB (heads/master)
 7f5a34d37554e19956c6ee7440b05f77182e8bd0 blasr_libcpp (p4-mainline-22-g7f5a34d)

**Comment by kemin711** [comment]
If I run the configure.py then manually edit the make file, I was able to compile successfully before.  You have made some changes.  I think the main problem is the pthread library.  The linking must be not clean.

**Comment by kemin711** [comment]
off your head, do you know which library is this from:
undefined reference to `HDFNewBasReader::Close()'

**Comment by pb-cdunn** [comment]
I do see an error, but not yours, and only after building.
```
$ make check
make -C test/cpp
make[1]: Entering directory 'pbdagcon/test/cpp'
make check
make[2]: Entering directory `pbdagcon/test/cpp'
g++ -O3 -std=c++11 -I. -I./ -Ipbdagcon/blasr_libcpp/alignment -Ipbdagcon/blasr_libcpp/pbdata -Ipbdagcon/blasr_libcpp/hdf -Ipbdagcon/src/cpp/third-party/boost_1_58_0-headersonly -Ipbdagcon/test/cpp/gtest-1.7.0/include -Ithird-party  -c -o TargetHitTest.o TargetHitTest.cpp
TargetHitTest.cpp:2:30: fatal error: DazAlnProvider.hpp: No such file or directory
 #include <DazAlnProvider.hpp>
```
I can fix that, but I'll need more info to solve *your* problem.

**Comment by pb-cdunn** [comment]
`blasr_libcpp/hdf/HDFNewBasReader.hpp:class HDFNewBasReader {`

**Comment by kemin711** [comment]
I got it.  I will manually fix the make file.

**Comment by pb-cdunn** [comment]
What is the manual fix? If we need to update configure.py, please give us a clue.

**Comment by kemin711** [comment]
After some manual work, still not fully there yet. Any clue?

g++ -Wl,--no-as-needed -o pbdagcon Alignment.o AlnGraphBoost.o BlasrM5AlnProvider.o main.o SimpleAligner.o  -L/home/kzhou/lib -L/usr/local/lib -lhdf5_cpp -lhdf5 -lpbihdf -lblasr -lpbdata
make[1]: *** No rule to make target `DB.o', needed by `dazcon'.  Stop.
make[1]: Leaving directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
make: *** [cpp] Error 2

**Comment by pb-cdunn** [comment]
My earlier error was old. I was on an old commit.

@kemin711, I need to know 2 pieces of information from you before I can consider this closed.

1. `git merge-base HEAD origin/master`
2. What is your manual fix?

**Comment by kemin711** [comment]
I am simply adding the needed include and linking requirement for HD5, and the blasr linking library

 -L/home/kzhou/lib
-lpbihdf -lblasr -lpbdata

**Comment by kemin711** [comment]
git merge-base HEAD origin/master
345498238728b741fbf5c10b96bf0904f8265ab1

**Comment by pb-cdunn** [comment]
You should not be building blasr_libcpp/hdf at all. HDF5 is not required.

How are you running `configure.py` now?

**Comment by kemin711** [comment]
Same as before: configure.py --no-pbbam

**Comment by kemin711** [comment]
At linking stage, it is asking for hdf5,

**Comment by pb-cdunn** [comment]
`--no-pbbam` is not enough. Try this:
    ./configure.py --boost --gtest --sub

See `travis.sh`.

**Comment by kemin711** [comment]
I am able to link up to the DB.c stage,  somehow my make system is having trouble with the 

vpath DB.c ${DAZZ_DB_SRC}
vpath QV.c ${DAZZ_DB_SRC}

**Comment by kemin711** [comment]
My system install boost in the default place, so there is no linking and include problem with boost that is taken care of. I will try the --gtest --sub option

**Comment by kemin711** [comment]
A lots more progress than before:
configure.py --no-pbbam --gtest --sub
hou/src/metag/pbdagcon/DALIGNER/align.c
/home/kzhou/src/metag/pbdagcon/DALIGNER/align.c:61:16: fatal error: DB.h: No such file or directory
 #include "DB.h"
                ^
compilation terminated.
make[1]: *** [align.o] Error 1
make[1]: Leaving directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
make: *** [cpp] Error 2

So the problem is not being able to find DB.h

**Comment by pb-cdunn** [comment]
In order to use only `--no-pbbam`, you would have to install the dependencies in your own way. Internally, we don't use git-submodules. They're mainly for the TravisCI build, but also to help you with integration.

`--sub` implies `--no-pbbam`, so you can drop `--no-pbbam`.

Your problem now is simply that you need to update your submodules. `make init-submodules` is one way.

**Comment by kemin711** [comment]
make init-submodule 
run successfully,
Entering directory `/home/kzhou/src/metag/pbdagcon/src/cpp'
cc -O3 -Wall -Wextra -fno-strict-aliasing -MMD -MP -I  -I/home/kzhou/src/metag/pbdagcon/DAZZ_DB -I/home/kzhou/src/metag/pbdagcon/DALIGNER -I/home/kzhou/src/metag/pbdagcon/blasr_libcpp/alignment -I/home/kzhou/src/metag/pbdagcon/blasr_libcpp/pbdata -isystem.//third-party  -c -o align.o /home/kzhou/src/metag/pbdagcon/DALIGNER/align.c
/home/kzhou/src/metag/pbdagcon/DALIGNER/align.c:61:16: fatal error: DB.h: No such file or directory
 #include "DB.h"

I think that the make is missing the include directory to DB.h

**Comment by kemin711** [comment]
The problem is the same after giving the make command.

**Comment by pb-cdunn** [comment]
Try

    ls /home/kzhou/src/metag/pbdagcon/DAZZ_DB
That should have `DB.h`.

**Comment by kemin711** [comment]
ls /home/kzhou/src/metag/pbdagcon/DAZZ_DB
Catrack.c    DBdust.c   DBstats.c                 fasta2DB.c   QV.h
DAM2fasta.c  DB.h       DBupgrade.Dec.31.2014.c   GNUmakefile  README
DB2fasta.c   DBrm.c     DBupgrade.Sep.25.2014.c   Makefile     simulator.c
DB2quiva.c   DBshow.c   DUSTupgrade.Jan.1.2015.c  quiva2DB.c
DB.c         DBsplit.c  fasta2DAM.c               QV.c

I also noticed that the original DALIGNER can be easily compiled.  The one inside pbdagcon cannot be compiled.

**Comment by pb-cdunn** [comment]
Oh! I see the problem:

    -I -I/home/kzhou/src/metag/pbdagcon/DAZZ_DB

We need an argument after the first `-I`. Let me see...

**Comment by kemin711** [comment]
That's the sort of manual fixing that I was doing before.

**Comment by pb-cdunn** [comment]
What version of `make` are you using?

    make --version

Or did you accidentally add `-I <no-arg>` yourself? Maybe you modified `INCDIRS`?

**Comment by kemin711** [comment]
I remember in my first successful make, I changed some of the:

INCDIRS := \
   ${DAZZ_DB_INCLUDE} \
   ${DALIGNER_INCLUDE} \
   ${LIBBLASR_INCLUDE} \
   ${LIBPBDATA_INCLUDE} \
   ${LIBPBIHDF_INCLUDE} \
   ${PBBAM_INCLUDE} \
   ${HDF5_INCLUDE} \
   ${HTSLIB_INCLUDE}
SYS_INCDIRS := \
   ${BOOST_INCLUDE} \
   ${THISDIR}/third-party
LIBDIRS := \
   ${LIBBLASR_LIB} \
   ${LIBPBDATA_LIB} \
   ${LIBPBIHDF_LIB} \
   ${PBBAM_LIB} \
   ${HDF5_LIB} \
   ${HTSLIB_LIB} \
   ${ZLIB_LIB}
LDLIBS+= \
   ${LIBBLASR_LIBFLAGS} \
   ${LIBPBDATA_LIBFLAGS} \
   ${LIBPBIHDF_LIBFLAGS} \
   ${PBBAM_LIBFLAGS} \
   ${HDF5_LIBFLAGS} \
   ${HTSLIB_LIBFLAGS} \
   ${ZLIB_LIBFLAGS} \
   ${PTHREAD_LIBFLAGS} \
   ${DL_LIBFLAGS}

**Comment by kemin711** [comment]
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

Is this too old?

**Comment by kemin711** [comment]
works after removing the dangling -I
CPPFLAGS += -MMD -MP

**Comment by kemin711** [comment]
I can make the binary successfully, but at run time, I must have messed up the linking environment.  Which means that my runtime and compile time linking is different:
pbdagcon
pbdagcon: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory

ldd pbdagcon
        linux-vdso.so.1 =>  (0x00007ffd4df9f000)
        libhdf5_cpp.so.10 => /usr/local/lib/libhdf5_cpp.so.10 (0x00007f622fcb7000)
        libhdf5.so.10 => /usr/local/lib/libhdf5.so.10 (0x00007f622f7db000)
        libpbihdf.so => not found
        libblasr.so => not found
        libpbdata.so => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f622f4d7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f622f1d1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f622efbb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f622ebf6000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f622e9dd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f622e7d9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f622ff17000)

**Comment by kemin711** [comment]
After fixing the linking issue in my runtime environment, I am having the same problem as my older build of pbdagcon

pbdagcon xx.m5
2015-08-10 11:21:25,384 INFO  [default] Multi-threaded. Input: xx.m5, Threads: 4
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)

Did I used the wrong input file?  Do you have a test data file?

**Comment by kemin711** [comment]
What type of threading did you use?  Native C++11 or pthread?

**Comment by pbjd** [comment]
I'm checking in a fix for it now ...

**Comment by kemin711** [comment]
I checked that your makefile does not mention pthread, the third-party, and dalign used pthread.  The linking flag order is important for pthread.
