### ISSUE TITLE
Heads-up on C++11

### ISSUE THREAD

**Issue by outpaddling** [PacificBiosciences/pbdagcon#39]
Just an FYI:

The majority of HPC clusters use some derivative of RHEL 6, which uses GCC 4.4, which does not support the C++11 standard.

There are no supported packages for newer GCC suites.  One would have to install it manually or use a 3rd-party RPM repository, which is risky from a support standpoint.

Hence, using C++11 features creates a hurdle for deploying software on many HPC clusters.

I'm not saying that C++11 features should not be used, but it would save a lot of man-hours on the user end and possibly improve the adoption of the software if it could work with GCC 4.4.

Cheers,

    Jason

**Comment by pb-cdunn** [comment]
Check out #91 for how @kortschak, managed to get a more recent gcc on a similar system.

Personally, I agree with you. I would use **Nim** for everything, which generates ordinary ISO C, and which can be installed anywhere easily. C# might be an option soon too. But people using C++ have very good reasons for C++11.

It's possible that we will eventually distribute prebuilt binaries. It is also possible we will revert to `-std=c++0x`. But not soon. Anyway, I'll mention your concern to management here.

**Comment by outpaddling** [comment]
Thanks for the link.  The devtoolset rpms are failing to install for us 
on CentOS 6.7, unfortunately.

Clang seems to have been dropped from the standard CentOS 6 yum repos.

I've done stone-age GCC installs in the past and may have to go that 
route again.  The problem with this approach is that it's not clearly 
documented or well-supported, and we usually discover problems with the 
installation many months down the road.

I realize that there are good reasons for using C++11, but they do have 
to be weighed against the need to support the platforms used by typical 
customers.  There are also very good reasons that most HPC clusters use 
RHEL 6 derivatives, mainly stability and support for running commercial 
software such as ANSYS, Matlab, etc.

I generally shy away from pre-build binaries due mainly to compatibility 
issues with shared lib versions across different Linux distros.

As long as the source code is available and well-organized on Github, 
I'll be content and will try to contribute.

**Comment by pb-cdunn** [comment]
If we switch blasr to -std=c++0x, could you verify that it works with your compiler? We still have some Centos6 nodes here, but just to be sure.

**Comment by outpaddling** [comment]
Absolutely.  I'm working on the blasr_libcpp package right now and most 
of it compiles with -std=c++0x patched into the makefiles. The 
compilation is failing for other reasons, but I'll confirm the whole 
blasr install once I resolve this.

**Comment by pb-cdunn** [comment]
Yeah, I've got that on this branch:
* https://github.com/pb-cdunn/blasr_libcpp/tree/c++0x

If you need any other changes, try to submit a pull-request, or point me to your fork.

**Comment by outpaddling** [comment]
Great, thanks.  I'll try the pull tomorrow.  I fixed the other issue I 
was having (an hdf5 installation problem) and then ran into some 
C++11isms.  I generated a patch to work around a constexpr and then ran 
into a lambda.

Have you tried building the c++0x branch on one of your CentOS 6 boxes?  
That might speed things up, but otherwise I'll continue to work on it 
and provide fixes as time permits.

My pkgsrc package at this point builds fine on FreeBSD 10.1 with clang 
3.4.1, but will need more patches for gcc 4.4.7 on CentOS.

Thanks,

     Jason

**Comment by pb-cdunn** [comment]
> Have you tried building the c++0x branch on one of your CentOS 6 boxes?

Sorry, I haven't. Might have time in a couple weeks.

**Comment by outpaddling** [comment]
Chris,

First, I want it to be known that I appreciate your rapid responses on 
all the issues I've opened this week.  Getting these pipelines working 
soon is important to us and it's great to have someone on the other end 
who acts so quickly to help us out.

I think we're close to having both the cDNA_primer and Falcon pipelines 
working, at least on our FreeBSD development servers. Once we work out 
the c++11 issues, we should be in a similar position to run it on our 
production CentOS cluster.

As a heads-up, I'll be sending a flurry of patches needed to build and 
install all the components separately instead of using git submodules 
and integrated source builds.  Let me know what would be the best way to 
submit those.  They're mostly minor improvements to the configure 
scripts and makefiles.

Regards,

     Jason

On 08/21/15 00:08, Christopher Dunn wrote:
>
>     Have you tried building the c++0x branch on one of your CentOS 6
>     boxes?
>
> Sorry, I haven't. Might have time in a couple weeks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PacificBiosciences/pbdagcon/issues/39#issuecomment-133287679>.
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Jason W. Bacon
   jwbacon@tds.net

   If a problem can be solved,
   there's no need to worry.
   
   If it cannot be solved, then
   worrying will do no good.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by pb-cdunn** [comment]
Hmm. I guess submit a pull-request to each repo separately. You can create an issue in PacificBiosciences/FALCON-integrate as a reference if you want.

Please avoid pull-requests on DALIGNER/DAZZ_DB. GitHub does something annoying; it sometimes alerts the top fork, which could bug Gene Myers. I imagine you have an install rule? We could apply that to our fork.

But honestly, it's all much simpler if you only *build* within those packages and use a separate package to *install* everything. Installation vary by system and team. Everybody seems to think there is one best way to do it, but believe me, nobody ever agrees.

I'm planning to add a `PREFIX=dir` argument to most *configure.py* scripts. That should take care of the most trivial use-case. Maybe that's what you had in mind? E.g.
* https://github.com/PacificBiosciences/blasr_libcpp/pull/43

**Comment by outpaddling** [comment]
Currently catching up on loose ends, so I'll explore the pull requests ASAP.

A separate package for installing is an interesting idea, but not an option for us.  We're using established package managers, currently FreeBSD ports (https://www.freebsd.org/ports/index.html) for FreeBSD and Pkgsrc (http://www.pkgsrc.org/) for CentOS and OS X.  Both have set stages for each package: fetch, extract, patch, build, stage, install.

You can see the development versions of my current FreeBSD ports here:

https://github.com/outpaddling/freebsd-ports-wip

My development pkgsrc packages will be here, once they're cleaned up a little:

http://wiki.netbsd.org/users/wiz/wip-users/

For now, I've done minimal patching to the source and have the packages handling the install themselves where there was no install target in the makefile.  This just gets us up and testing sooner.  It would be better to push the install upstream to your source eventually, so I'll do more extensive patches as the packages mature.  These same patches will make it easier for others create Debian packages, MacPorts, Homebrew packages, etc. in case that's of interest to you or other customers.  All the package managers follow basically the same approach, so upstream changes that aid one of them will aid all of them.

The PREFIX variable (or a --prefix= flag) would probably be helpful, especially if the configure scripts also respects DESTDIR for staging.

**Comment by pb-cdunn** [comment]
> A separate package for installing is an interesting idea, but not an option for us.

Sure it is! Instead of fetching pbdagcon from github, you fetch the integration package from github and run 'git submodule update --init'. pbdagcon will be in a subdir of integration package. You can follow the same pattern for other pacakges.

> ports/pkgsrc

That should work fine. Just run `configure.py && make` as the build step. I have no problem with adding a rule to `make install` into PREFIX.

> DESTDIR for staging

What is that for? I see nothing about staging in pkgsrc docs. If the purpose is to build out-of-source, I have a simple solution for that too.

**Comment by outpaddling** [comment]
On 08/24/15 16:26, Christopher Dunn wrote:
>
>     A separate package for installing is an interesting idea, but not
>     an option for us.
>
> Sure it is! Instead of fetching pbdagcon from github, you fetch the 
> integration package from github and run 'git submodule update --init'. 
> pbdagcon will be in a subdir of integration package. You can follow 
> the same pattern for other pacakges.
>
>     ports/pkgsrc
>
> That should work fine. Just run |configure.py && make| as the build 
> step. I have no problem with adding a rule to |make install| into PREFIX.
>
I didn't mean that it's not technically feasible, but that it wouldn't 
be considered acceptable practice under most package managers.

Packages are supposed to be made as modular and independent as possible, 
so that, for instance, any package that requires blasr_libcpp can 
automatically install it as a dependency, without installing anything else.

Also, if multiple packages are installed that require blasr_libcpp, they 
would all share a single blasr_libcpp installation rather than install 
redundant copies of their own.  This does mean that they are tied 
together by a common dependency, but that's considered preferable to 
duplicate installations in the packaging community. In the rare cases 
where we really need two conflicting versions of something, there are 
simple workarounds, like installing one under a non-standard prefix.
>
>     DESTDIR for staging
>
> What is that for? I see nothing about staging in pkgsrc docs. If the 
> purpose is to build out-of-source, I have a simple solution for that too.
>
Most package managers now do staged installs, meaning that the source 
dist installs to a staging area instead of the final prefix. The package 
manager then uses a consistent framework to copy from the staging area 
to the final install prefix.  The allows the package manager to 
deterministically detect any collisions between packages.

http://www.gnu.org/prep/standards/html_node/DESTDIR.html

BTW, I just noticed that my last commit partially failed, and almost 
none of the PacBio ports were pushed.  It's fixed now, so you can 
examine the latest ports such as 
https://github.com/outpaddling/freebsd-ports-wip/tree/master/biology/blasr_libcpp 
if you like.

Cheers,

     Jason

**Comment by pb-cdunn** [comment]
> Packages are supposed to be made as modular and independent as possible...

But only when they're stable. Ours are not at that point yet. If we were versioning, we would be bumping major-version numbers constantly. I worry that "packaging" these things will cause people to assume that we've guaranteed some contracts. We don't promise backward-compatibility at all -- only consistency amongst package "versions" released in the same integration package.

> Also, if multiple packages are installed that require blasr_libcpp ...

We will eventually release those with a single integration package. To me, it makes more sense to consider a large set of pacbio repos as a "package" in the rpm/pkgsrc/port sense.

**Comment by outpaddling** [comment]
I don't intend to move these ports/packages beyond the WIP 
(work-in-progress) collections until there are regular tagged releases.  
But, I think developing these packages now will help upstream 
development evolve, for reasons I mentioned before, and some that have 
become apparent, e.g. the need for install targets in some of the 
repos.  It'll all work it out in time.  Always does...

Cheers,

     Jason

**Comment by pb-cdunn** [comment]
:sunglasses:

**Comment by pb-cdunn** [comment]
You can try the c++0x branch. It *might* work with your compiler. If so, we'll leave the branch around, but we cannot guarantee that it will get fixes etc. Hopefully it works for you.

There is also a PREFIX setting now, to avoid having to specify every dependency separately. I have not created the 'install' targets yet. Maybe in a couple week.

**Comment by outpaddling** [comment]
Thanks.  FYI, I just discovered that someone recently got the pkgsrc GCC 
packages working well on CentOS 6, so we now have relatively easy and 
reliable way to install GCC 4.8 and 4.9.  I will still attempt to make 
the pkgsrc packages compatible with GCC 4.4, though.  As we've seen, the 
required changes are minimal and a GCC package adds a huge tree of 
dependencies that's likely to cause frequent problems for end-users.

Regarding PacBio support for CentOS, below is some food for thought.  
It's from a recent survey of XSEDE campus champions regarding the OS and 
management tools they use for their local clusters.  I would expect 
CentOS 7 to be dominant in 2-3 years when most commercial software 
vendors have caught up and most of these clusters have been through an 
upgrade cycle.

Regards,

     Jason

UWM Central IT                  CentOS 6.7, FreeBSD Yum, pkgsrc, FreeBSD 
ports
UWM LIGO                        Debian              Debian 
packages,ad-hoc, Puppet
San Diego Supercomputing Center CentOS 6.4, 6.6     Rocks rolls
WVU                             RHEL 6.6 Cobbler, Ansible
Michigan Tech                   CentOS 6.3 Rolls
UNC-CH                          RHEL 5.11 Platform
U Iowa                          CentOS 5.11, 6.4    Rocks, Puppet
Wharton School, U Penn          RHEL 7.1 Kickstart, Ansible
St. Louis U                     CentOS 6.7          Bright Cluster Manager
UCF                             CentOS 7            Yum, ad-hoc
Center for sim and mod, U Pitt  RHEL 6              Penguin Scyld 
ClusterWare,ad-hoc, Warewolf, Spack
U Louisville                    CentOS 6.6          Yum, ad-hoc
Tufts                           RHEL 6.5            Puppet, ad-hoc
Harvard                         CentOS 6.5          Helmod, Puppet
U Arkansas                      CentOS 6.5 xCAT
UT-MD Anderson Cancer Center    RHEL 6.4, 6.5       Yum, CMU, PCM, ad-hoc
Coastal Carolina U              CentOS 6.6 Kickstart, ad-hoc
Case Western                    CentOS 6.6, 6.7 xCAT
Oklahoma State                  CentOS 6.3, 6.6     Yum, ad-hoc
Lehigh U                        CentOS 6.6 Saltstack
Marshall U                      CentOS 6.6          Rocks, yum, ad-hoc, 
DevOp
U Delaware                      Scientific Linux 6.6, CentOS 
6.5          Ad-hoc
Nebraska                        Scientific Linux 6.6 Cobbler, Puppet, ad-hoc
Southner Illinois U             CentOS 6            Rocks
W Virginia State                CentOS 6.6 Act-utils
Temple U                        RHEL 6.2, CentOS 6.6 Rocks, custom 
scripts, ad-hoc
UC Irvine                       CentOS 6.6 -> Debian Perceus, Rocks, 
ad-hoc, Warewulf
U Utah Center for HPC           RHEL6 -> CentOS 6 Cluster OS, Spacewalk, 
ad-hoc
Rutgers                         Ubuntu -> CentOS fai/ssh -> kickstart, 
pdsh, puppet/ansible
MSI U Minn                      CentOS 6.7          HP Insight, Puppet
UC Riverside                    CentOS 6.7, 5.11, SL Perceus, Warewulf
U Alabama Birmingham            CentOS 5.11, 7.1    Rocks, Bright CM, 
Puppet,Chef, ad-hoc, easybuild
Montana State                   CentOS 6.7          Bright CM, Ansible
U Hawaii                        CentOS 6.5          Cray ACE
U of Washington                 RHEL 6 -> CentOS xCAT, ad-hoc?
Indiana U                       RHEL 6.7            xCAT, XNIT
Florida State RCC               RHEL 7 -> CentOS 7 Foreman, Puppet, RHEL 
Satellite, Katello
U Oklahoma                      CentOS 6.7, 7.1     Yum, Puppet, Salt

**Comment by pb-cdunn** [comment]
Email is not editable in GitHub, so I've copied and added markdown:
```
UWM Central IT                  CentOS 6.7, FreeBSD Yum, pkgsrc, FreeBSD 
ports
UWM LIGO                        Debian              Debian 
packages,ad-hoc, Puppet
San Diego Supercomputing Center CentOS 6.4, 6.6     Rocks rolls
WVU                             RHEL 6.6 Cobbler, Ansible
Michigan Tech                   CentOS 6.3 Rolls
UNC-CH                          RHEL 5.11 Platform
U Iowa                          CentOS 5.11, 6.4    Rocks, Puppet
Wharton School, U Penn          RHEL 7.1 Kickstart, Ansible
St. Louis U                     CentOS 6.7          Bright Cluster Manager
UCF                             CentOS 7            Yum, ad-hoc
Center for sim and mod, U Pitt  RHEL 6              Penguin Scyld 
ClusterWare,ad-hoc, Warewolf, Spack
U Louisville                    CentOS 6.6          Yum, ad-hoc
Tufts                           RHEL 6.5            Puppet, ad-hoc
Harvard                         CentOS 6.5          Helmod, Puppet
U Arkansas                      CentOS 6.5 xCAT
UT-MD Anderson Cancer Center    RHEL 6.4, 6.5       Yum, CMU, PCM, ad-hoc
Coastal Carolina U              CentOS 6.6 Kickstart, ad-hoc
Case Western                    CentOS 6.6, 6.7 xCAT
Oklahoma State                  CentOS 6.3, 6.6     Yum, ad-hoc
Lehigh U                        CentOS 6.6 Saltstack
Marshall U                      CentOS 6.6          Rocks, yum, ad-hoc, 
DevOp
U Delaware                      Scientific Linux 6.6, CentOS 
6.5          Ad-hoc
Nebraska                        Scientific Linux 6.6 Cobbler, Puppet, ad-hoc
Southner Illinois U             CentOS 6            Rocks
W Virginia State                CentOS 6.6 Act-utils
Temple U                        RHEL 6.2, CentOS 6.6 Rocks, custom 
scripts, ad-hoc
UC Irvine                       CentOS 6.6 -> Debian Perceus, Rocks, 
ad-hoc, Warewulf
U Utah Center for HPC           RHEL6 -> CentOS 6 Cluster OS, Spacewalk, 
ad-hoc
Rutgers                         Ubuntu -> CentOS fai/ssh -> kickstart, 
pdsh, puppet/ansible
MSI U Minn                      CentOS 6.7          HP Insight, Puppet
UC Riverside                    CentOS 6.7, 5.11, SL Perceus, Warewulf
U Alabama Birmingham            CentOS 5.11, 7.1    Rocks, Bright CM, 
Puppet,Chef, ad-hoc, easybuild
Montana State                   CentOS 6.7          Bright CM, Ansible
U Hawaii                        CentOS 6.5          Cray ACE
U of Washington                 RHEL 6 -> CentOS xCAT, ad-hoc?
Indiana U                       RHEL 6.7            xCAT, XNIT
Florida State RCC               RHEL 7 -> CentOS 7 Foreman, Puppet, RHEL 
Satellite, Katello
U Oklahoma                      CentOS 6.7, 7.1     Yum, Puppet, Salt
```

**Comment by pb-cdunn** [comment]
That's a useful list of University systems. But at this point, I don't think we can move away from C++11.

Hopefully, [pitchfork](https://github.com/PacificBiosciences/pitchfork/wiki) will solve most integration problems for most users.
