### ISSUE TITLE
output qv of correctedf.fastq by coverage of subread instead of "9"

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/pbdagcon#42]
hi,
      I  find that quality value of corrected.fastq  is all "9",but I want the more accurate value. example:
            I have one subread A waitting for be corrected,
                        when ten subreads is mapped to A,the qv of corrected.fastq is C.
                        when twenty  subreads is mapped to A,the qv of corrected.fastq is D.
       So ascii of D should be greater than C. but if use "pbdagcon",the value is both "9",so I cannot diff them.
    
So what I should do ?

Thanks!

**Comment by pbjd** [comment]
QV values are actually not computed as part of correction.  The fastq file that's generated contains mocked up values (arbitrarily chosen to be 9) and only exists for interfacing with celera-assembler.  In practice, the corrected reads fall in the range of QV 17- 20, YMMV.  The main purpose of correction is to push the read accuracy up enough so it's suitable for assembly.  For obtaining more accurate QV values, you can try https://github.com/PacificBiosciences/pbccs

**Comment by orangeSi** [comment]
my purpose is get real qv of corrected.fastq  regardless the mapped coverage (correction of HAP3 will trim low mapped coverage of region ,i don't want to trim ),after  got corrected.fastq then use proovread to correct the low qv region of corrected.fastq regard less the high qv region .

**Comment by pbjd** [comment]
There is an option to pbdagcon, '-c', that allows you to reduce the minimum coverage required to maintain the corrected read (default is 6).  Lowering too much, however, can allow chimeric elements to seep through.

**Comment by orangeSi** [comment]
'-c' mean the number subread that have overlap with seed ? or the average depth of subreads  when subreads map to one seed , ?

**Comment by pbjd** [comment]
It's the number of subreads that overlap and match with the consensus base at any particular location in the seed.  If the consensus base does not have at least '-c' matching subreads to support, the corrected read will be cut at that location.
