### ISSUE TITLE
Problem about compiling DAGCon

### ISSUE THREAD

**Issue by baoe** [PacificBiosciences/pbdagcon#49]
Hi,

I'm currently trying to compile DAGCon from source, and meet this compilation error:
```cpp
g++ -o pbdagcon Alignment.o AlnGraphBoost.o BlasrM5AlnProvider.o main.o SimpleAligner.o -L /rhome/ebao/pbdagcon-master/blasr_libcpp/alignment -L /rhome/ebao/pbdagcon-master/blasr_libcpp/pbdata  -lblasr -lpbdata      -lpthread
/usr/bin/ld: warning: libpbihdf.so, needed by /rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so, not found (try using -rpath or -rpath-link)
/rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so: undefined reference to `vtable for HDFData'
/rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::H5File::~H5File()'
/rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::DataSet::getSpace() const'
/rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so: undefined reference to `H5check_version'
/rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so: undefined reference to `H5::DSetCreatPropList::DSetCreatPropList()'
/rhome/ebao/pbdagcon-master/blasr_libcpp/alignment/libblasr.so: undefined reference to `HDFNewBasReader::Close()'
......
```
Looks like libblasr.so needs many things but it could not find them, so I try to delete libblasr.so. The compilation could finish, but when I run the executable pbdagcon, I get this error message:
```
./pbdagcon: error while loading shared libraries: libpbdata.so: cannot open shared object file: No such file or directory
```
Could you help me to fix this problem? 

BTW: I find the compilation of DAGCon is quite complicated, so I'm wondering if it could be simplified, and/or the executable could be provided directly.

Thank you,
Bao

**Comment by pb-cdunn** [comment]
Try this:
* https://github.com/PacificBiosciences/pbdagcon/blob/master/README.md

That should build with static archives instead of shared libraries, currently not supported for pbdagcon. Are you on a Mac? If not, why do you need shared libraries?

More important, what were your arguments to `configure.py`? And what commands did you issue to build? For an example, see [`travis.sh`](https://github.com/PacificBiosciences/pbdagcon/blob/master/travis.sh).

**Comment by baoe** [comment]
Hi, Chris,

Thank you for your reply. I just followed the README instructions in pbdagcon:
1. ./configure.py --boost --gtest --sub --no-pbbam
2. make init-submodule
3. make
4. make check
5. cd src/cpp
6. ./pbdagcon --help

Sometimes, I could finish making and checking pbdagcon in step 4, but I cannot run it in step 6:
./pbdagcon: error while loading shared libraries: libblasr.so: cannot open shared object file: No such file or directory

Is it because my system does not have the shared libs? If it is, why step 4 could pass?
Also, I don't know why I cannot always finish making pbdagcon.

Bao

________________________________

**Comment by pb-cdunn** [comment]
Which commit? `git rev-parse HEAD`

**Comment by pb-cdunn** [comment]
You probably just need to set `LD_LIBRARY_PATH` (or `DYLD_LIBRARY_PATH` on OSX). Closing.
