### ISSUE TITLE
gtest url invalid

### ISSUE THREAD

**Issue by gt1** [PacificBiosciences/pbdagcon#58]
The URL used for gtest in configure.py seems to have become invalid as Google Code was shut down. I would suggest to replace it by https://github.com/google/googletest/archive/release-1.7.0.zip (or in fact version 1.8.0 if you do not specifically rely on version 1.7.0).

**Comment by pb-cdunn** [comment]
Thanks. Soon I hope.

**Comment by mhsieh** [comment]
that does happen, our bad.

**Comment by mhsieh** [comment]
Thank you @gt1 I am closing this now.
