### ISSUE TITLE
Install error pbdagcon

### ISSUE THREAD

**Issue by xogur** [PacificBiosciences/pbdagcon#59]
Hi,

I am trying to install pbdagcon. But, I get an error message like at below. Can Anybody help me to figure it out? Thank you!

xogur
```sh
$ pip install git+https://github.com/PacificBiosciences/pbdagcon.git#pbdagcon
Collecting git+https://github.com/PacificBiosciences/pbdagcon.git#pbdagcon
Cloning https://github.com/PacificBiosciences/pbdagcon.git to /private/var/folders/l7/7kh64jhj0_7gbr_c7k2xk1980000gp/T/pip-j1QCba-build
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
IOError: [Errno 2] No such file or directory: '/private/var/folders/l7/7kh64jhj0_7gbr_c7k2xk1980000gp/T/pip-j1QCba-build/setup.py'
----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l7/7kh64jhj0_7gbr_c7k2xk1980000gp/T/pip-j1QCba-build/
```

**Comment by pb-cdunn** [comment]
pbdagcon is not Python! :smile_cat:

**Comment by xogur** [comment]
Thank you pb-cdunn!

I tried to install it again according to its instruction. However, I got an error that "'H5Cpp.h' file not found". But, there is the H5Cpp.h on my path. Could you please see my log at below and advise me how to solve this problem? For reference, I am using OS X (10.11.4) and I did install the blasr successfully using the same hdf5 path. Thank you!

xogur

$ ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/usr/local/Cellar/hdf5/1.8.17/include/ HDF5_LIB=/usr/local/Cellar/hdf5/1.8.17/lib/
uname -s
uname='Darwin'
writing to '/Users/THKang/pbdagcon/defines.mk'
"""
DALIGNER_INCLUDE     ?= ${DALIGNER_SRC}
DALIGNER_SRC         ?= /Users/THKang/pbdagcon/DALIGNER
DAZZ_DB_INCLUDE      ?= ${DAZZ_DB_SRC}
DAZZ_DB_SRC          ?= /Users/THKang/pbdagcon/DAZZ_DB
HDF5_INCLUDE         ?= /usr/local/Cellar/hdf5/1.8.17/include/
HDF5_LIB             ?= /usr/local/Cellar/hdf5/1.8.17/lib/
LIBBLASR_INCLUDE     ?= /Users/THKang/pbdagcon/blasr_libcpp/alignment
LIBBLASR_LIB         ?= /Users/THKang/pbdagcon/blasr_libcpp/alignment
LIBBLASR_LIBFLAGS    ?= -lblasr
LIBPBDATA_INCLUDE    ?= /Users/THKang/pbdagcon/blasr_libcpp/pbdata
LIBPBDATA_LIB        ?= /Users/THKang/pbdagcon/blasr_libcpp/pbdata
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_INCLUDE    ?= 
LIBPBIHDF_LIB        ?= 
PTHREAD_LIBFLAGS     ?= -lpthread
LDLIBS+=-lrt
"""

$ make init-submodule
/Applications/Xcode.app/Contents/Developer/usr/bin/make update-submodule
git submodule update --init
Submodule 'DALIGNER' (git://github.com/PacificBiosciences/DALIGNER.git) registered for path 'DALIGNER'
Submodule 'DAZZ_DB' (git://github.com/PacificBiosciences/DAZZ_DB.git) registered for path 'DAZZ_DB'
Submodule 'blasr_libcpp' (git://github.com/PacificBiosciences/blasr_libcpp.git) registered for path 'blasr_libcpp'
Cloning into 'DALIGNER'...
remote: Counting objects: 727, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 727 (delta 0), reused 0 (delta 0), pack-reused 724
Receiving objects: 100% (727/727), 735.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (490/490), done.
Checking connectivity... done.
Submodule path 'DALIGNER': checked out '583de37361afef71dee572b7ba0088ea77afb494'
Cloning into 'DAZZ_DB'...
remote: Counting objects: 589, done.
remote: Total 589 (delta 0), reused 0 (delta 0), pack-reused 589
Receiving objects: 100% (589/589), 497.28 KiB | 207.00 KiB/s, done.
Resolving deltas: 100% (402/402), done.
Checking connectivity... done.
Submodule path 'DAZZ_DB': checked out '7954b44be028a864aeb611c22a3acd9b0cd95eed'
Cloning into 'blasr_libcpp'...
remote: Counting objects: 4422, done.
remote: Total 4422 (delta 0), reused 0 (delta 0), pack-reused 4422
Receiving objects: 100% (4422/4422), 2.04 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (2968/2968), done.
Checking connectivity... done.
Submodule path 'blasr_libcpp': checked out '40b17dd868c70b91e0730c9c5a125563411e848d'
/Applications/Xcode.app/Contents/Developer/usr/bin/make build-submodule
cd blasr_libcpp; NOHDF=1 NOPBBAM=1 ./configure.py
uname -s
uname='Darwin'
writing to '/Users/THKang/pbdagcon/blasr_libcpp/pbdata/libconfig.h'
"""

"""
writing to 'defines.mk'
"""

EXTRA_LDFLAGS        := -flat_namespace
SH_LIB_EXT           := .dylib

LIBPBDATA_INC ?=../pbdata
LIBPBIHDF_INC ?=../hdf
LIBBLASR_INC  ?=../alignment
LIBPBDATA_LIB ?=/Users/THKang/pbdagcon/blasr_libcpp/pbdata/
LIBPBIHDF_LIB ?=/Users/THKang/pbdagcon/blasr_libcpp/hdf/
LIBBLASR_LIB  ?=/Users/THKang/pbdagcon/blasr_libcpp/alignment/
nohdf         ?=1

# Use PREFIX dir, if available.
INCLUDES      += ${PREFIX_INC}
LIBS          += ${PREFIX_LIB}
"""
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C blasr_libcpp/pbdata libconfig.h
make[2]: `libconfig.h' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C blasr_libcpp/pbdata libpbdata.a
c++ -std=c++11 -pedantic -Wall -Wextra    -c alignment/CmpAlignment.cpp -o CmpAlignment.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c amos/AfgBasWriter.cpp -o AfgBasWriter.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c CCSSequence.cpp -o CCSSequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c ChangeListID.cpp -o ChangeListID.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c CommandLineParser.cpp -o CommandLineParser.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c DNASequence.cpp -o DNASequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c FASTAReader.cpp -o FASTAReader.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c FASTASequence.cpp -o FASTASequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c FASTQReader.cpp -o FASTQReader.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c FASTQSequence.cpp -o FASTQSequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c GFFFile.cpp -o GFFFile.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c loadpulses/MetricField.cpp -o MetricField.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c loadpulses/MovieAlnIndexLookupTable.cpp -o MovieAlnIndexLookupTable.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c MD5Utils.cpp -o MD5Utils.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c metagenome/TitleTable.cpp -o TitleTable.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c NucConversion.cpp -o NucConversion.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c PackedDNASequence.cpp -o PackedDNASequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c qvs/QualityTransform.cpp -o QualityTransform.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c qvs/QualityValue.cpp -o QualityValue.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/AcqParams.cpp -o AcqParams.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/BaseFile.cpp -o BaseFile.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/HoleXY.cpp -o HoleXY.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/PulseBaseCommon.cpp -o PulseBaseCommon.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/PulseFile.cpp -o PulseFile.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/ReadType.cpp -o ReadType.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/RegionAnnotation.cpp -o RegionAnnotation.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/RegionAnnotations.cpp -o RegionAnnotations.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/RegionTable.cpp -o RegionTable.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/RegionTypeMap.cpp -o RegionTypeMap.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/ScanData.cpp -o ScanData.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c reads/ZMWGroupEntry.cpp -o ZMWGroupEntry.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c ReverseCompressIndex.cpp -o ReverseCompressIndex.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c saf/AlnGroup.cpp -o AlnGroup.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c saf/MovieInfo.cpp -o MovieInfo.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c saf/RefGroup.cpp -o RefGroup.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c saf/RefInfo.cpp -o RefInfo.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c sam/ReadGroup.cpp -o ReadGroup.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c sam/ReferenceSequence.cpp -o ReferenceSequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c sam/SAMAlignment.cpp -o SAMAlignment.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c sam/SAMHeader.cpp -o SAMHeader.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c sam/SAMKeywordValuePair.cpp -o SAMKeywordValuePair.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c SMRTSequence.cpp -o SMRTSequence.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c StringUtils.cpp -o StringUtils.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c utils/BitUtils.cpp -o BitUtils.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c utils/SMRTReadUtils.cpp -o SMRTReadUtils.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c utils/SMRTTitle.cpp -o SMRTTitle.o
c++ -std=c++11 -pedantic -Wall -Wextra    -c utils/TimeUtils.cpp -o TimeUtils.o
ar rc libpbdata.a CmpAlignment.o AfgBasWriter.o CCSSequence.o ChangeListID.o CommandLineParser.o DNASequence.o FASTAReader.o FASTASequence.o FASTQReader.o FASTQSequence.o GFFFile.o MetricField.o MovieAlnIndexLookupTable.o MD5Utils.o TitleTable.o NucConversion.o PackedDNASequence.o QualityTransform.o QualityValue.o AcqParams.o BaseFile.o HoleXY.o PulseBaseCommon.o PulseFile.o ReadType.o RegionAnnotation.o RegionAnnotations.o RegionTable.o RegionTypeMap.o ScanData.o ZMWGroupEntry.o ReverseCompressIndex.o AlnGroup.o MovieInfo.o RefGroup.o RefInfo.o ReadGroup.o ReferenceSequence.o SAMAlignment.o SAMHeader.o SAMKeywordValuePair.o SMRTSequence.o StringUtils.o BitUtils.o SMRTReadUtils.o SMRTTitle.o TimeUtils.o
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C blasr_libcpp/alignment libblasr.a
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/AlignmentUtils.cpp -o AlignmentUtils.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/BaseScoreFunction.cpp -o BaseScoreFunction.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/ExtendAlign.cpp -o ExtendAlign.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/GuidedAlign.cpp -o GuidedAlign.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/IDSScoreFunction.cpp -o IDSScoreFunction.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/KBandAlign.cpp -o KBandAlign.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/QualityValueScoreFunction.cpp -o QualityValueScoreFunction.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/ScoreMatrices.cpp -o ScoreMatrices.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/sdp/SDPFragment.cpp -o SDPFragment.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/sdp/SparseDynamicProgramming.cpp -o SparseDynamicProgramming.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/alignment/StringToScoreMatrix.cpp -o StringToScoreMatrix.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/anchoring/BWTSearch.cpp -o BWTSearch.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/anchoring/ClusterProbability.cpp -o ClusterProbability.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/anchoring/Coordinate.cpp -o Coordinate.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/anchoring/FindMaxInterval.cpp -o FindMaxInterval.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/sorting/DifferenceCovers.cpp -o DifferenceCovers.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/sorting/LightweightSuffixArray.cpp -o LightweightSuffixArray.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/sorting/MultikeyQuicksort.cpp -o MultikeyQuicksort.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c algorithms/sorting/qsufsort.cpp -o qsufsort.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/Alignment.cpp -o Alignment.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/AlignmentCandidate.cpp -o AlignmentCandidate.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/AlignmentContext.cpp -o AlignmentContext.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/AlignmentMap.cpp -o AlignmentMap.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/AlignmentStats.cpp -o AlignmentStats.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/CmpFile.cpp -o CmpFile.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/FilterCriteria.cpp -o FilterCriteria.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignment/SAMToAlignmentCandidateAdapter.cpp -o SAMToAlignmentCandidateAdapter.o
datastructures/alignment/SAMToAlignmentCandidateAdapter.cpp:94:50: warning: all
      paths through this function will call itself [-Winfinite-recursion]
                      AlignmentCandidate<> &aln) {
                                                 ^
1 warning generated.
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignmentset/SAMQVConversion.cpp -o SAMQVConversion.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/alignmentset/SAMSupplementalQVList.cpp -o SAMSupplementalQVList.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/anchoring/AnchorParameters.cpp -o AnchorParameters.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/anchoring/ClusterList.cpp -o ClusterList.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/anchoring/MatchPos.cpp -o MatchPos.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c datastructures/anchoring/WeightedInterval.cpp -o WeightedInterval.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c files/BaseSequenceIO.cpp -o BaseSequenceIO.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c files/CCSIterator.cpp -o CCSIterator.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c files/FragmentCCSIterator.cpp -o FragmentCCSIterator.o
c++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual    -c files/ReaderAgglomerate.cpp -o ReaderAgglomerate.o
In file included from files/ReaderAgglomerate.cpp:1:
In file included from files/ReaderAgglomerate.hpp:14:
In file included from files/../../hdf/HDFBasReader.hpp:18:
files/../../hdf/HDFArray.hpp:7:10: fatal error: 'H5Cpp.h' file not found
#include <H5Cpp.h>
         ^
1 error generated.
make[2]: *** [ReaderAgglomerate.o] Error 1
make[1]: *** [build-submodule] Error 2
make: *** [init-submodule] Error 2

$ pwd
/usr/local/Cellar/hdf5/1.8.17/include
$ ls
H5ACpublic.h	H5DataSpace.h	H5FDmulti.h	H5Ipublic.h	H5PropList.h
H5AbstractDs.h	H5DataType.h	H5FDpublic.h	H5LTpublic.h	H5Rpublic.h
H5Apublic.h	H5DcreatProp.h	H5FDsec2.h	H5Library.h	H5Spublic.h
H5ArrayType.h	H5Dpublic.h	H5FDstdio.h	H5Location.h	H5StrType.h
H5AtomType.h	H5DxferProp.h	H5FaccProp.h	H5Lpublic.h	H5TBpublic.h
H5Attribute.h	H5EnumType.h	H5FcreatProp.h	H5MMpublic.h	H5Tpublic.h
H5Classes.h	H5Epubgen.h	H5File.h	H5Object.h	H5VarLenType.h
H5CommonFG.h	H5Epublic.h	H5FloatType.h	H5OcreatProp.h	H5Zpublic.h
H5CompType.h	H5Exception.h	H5Fpublic.h	H5Opublic.h	H5api_adpt.h
**H5Cpp.h**		H5FDcore.h	H5Gpublic.h	H5PLextern.h	H5overflow.h
H5CppDoc.h	H5FDdirect.h	H5Group.h	H5PLpublic.h	H5pubconf.h
H5Cpublic.h	H5FDfamily.h	H5IMpublic.h	H5PTpublic.h	H5public.h
H5DOpublic.h	H5FDlog.h	H5IdComponent.h	H5PacketTable.h	H5version.h
H5DSpublic.h	H5FDmpi.h	H5Include.h	H5Ppublic.h	hdf5.h
H5DataSet.h	H5FDmpio.h	H5IntType.h	H5PredType.h	hdf5_hl.h

**Comment by pb-cdunn** [comment]
Works for me.... And we have the same git-commits. Hmmm...

`alignment/files/ReaderAgglomerate.cpp` should not be compiled, based on the flags you have used. It should be filtered out of `alignement/makefile` by:
```
 28 sources := $(shell find ${THISDIR} -name '*.cpp')
 29
 30 ifdef nohdf
 31 sources := $(filter-out ${THISDIR}files/% ${THISDIR}utils/FileOfFileNames.cpp ${THISDIR}format/SAMHeaderPrinter.cpp, $(sources))
 32 endif
```
Oh, I see. UNIX `find` now works differently on OSX than on Linux. OSX retains a trailing slash in the first argument to `find`, so when we apply the filter in the makefile the paths do not match. One has `alignment//files/Reader...`; the other has `alignment/files/Reader...`.

Looking for a solution...

**Comment by pb-cdunn** [comment]
There is a problem with the gtest zipfile, but the basic code should build now.
