### ISSUE TITLE
Enable multithreading to use std::thread: Operation not permitted

### ISSUE THREAD

**Issue by jhtrujillo** [PacificBiosciences/pbdagcon#64]
Hi, 

I am running the following comand : 

pbdagcon -j 4 -a mapped.pre > corrected.fasta

But I got this: 

Terminate called after throwing an instance of 'std::system_error'
what():  Enable multithreading to use std::thread: Operation not permitted

May you help me?

Thanks!

**Comment by pb-cdunn** [comment]
You have to compile with something like `-pthreads`. You haven't said anything about how you built this, so we can't easily help you.

**Comment by jhtrujillo** [comment]
Hi, Thanks! 

I solved the problem by updating my version of C ++.
